project_id = "kmqgbaaftwlqxhtfggeg"

[functions.analyze-company]
verify_jwt = true

[functions.bmc-chat]
verify_jwt = true

[functions.business-overview-chat]
verify_jwt = true

[functions.competitor-chat]
verify_jwt = true

[functions.seed-frameworks]
verify_jwt = false

[functions.recommend-frameworks]
verify_jwt = true

[functions.generate-framework-report]
verify_jwt = true

[functions.strategy-coach-chat]
verify_jwt = true

[functions.research-competitors]
verify_jwt = true