import type { SupabaseClient } from "@supabase/supabase-js";
import type { AgentRunner } from "../agent/runner.js";
import { ClaudeAgentRunner, OpenRouterChatRunner } from "../agent/runner.js";
import { asRecord } from "../db/json.js";
import { SECTION_LABELS, isSectionKey, type SectionKey } from "../domain/sections.js";
import { FeedRunner } from "../feeds/feed-runner.js";
import type { EvidenceCandidate, FeedRuntimeConfig } from "../feeds/types.js";
import type { AgentJob } from "../queue/types.js";
import { chooseModelRoute } from "./canvas-section-analysis.js";

interface ModelRoute {
  account_id?: string | null;
  route_key?: string | null;
  task_class?: string | null;
  provider: string;
  model_name: string;
  params?: Record<string, unknown> | null;
  cost_per_1k_in: number | null;
  cost_per_1k_out: number | null;
}

interface BusinessContext {
  id: string;
  company_name: string | null;
  industry: string | null;
  website?: string | null;
}

interface CompanyEntity {
  id: string;
  name: string;
  website_url: string | null;
  description: string | null;
  industry: string | null;
  is_competitor: boolean;
}

interface ExtractedClaim {
  sectionKey: SectionKey;
  text: string;
  confidence: number;
  evidenceIndex: number;
}

export type VerificationStatus = "confirmed" | "unsupported" | "contradicted";

interface VerifiedClaim extends ExtractedClaim {
  status: VerificationStatus;
  reason: string;
  evidenceId: string;
}

interface ResearchSubject {
  context: BusinessContext;
  targetName: string;
  targetUrl: string;
  competitorId: string | null;
  runType: "company_research" | "competitor_research";
  cacheKey: string;
  runInput: Record<string, unknown>;
  canvasNotes: string;
}

export interface CompanyResearchDependencies extends FeedRuntimeConfig {
  client: SupabaseClient;
  runner?: AgentRunner;
  feedRunner?: Pick<FeedRunner, "refresh">;
  openRouterApiKey?: string;
  fetch?: typeof fetch;
}

export class CompanyResearchHandler {
  private readonly runner: AgentRunner;
  private readonly feedRunner: Pick<FeedRunner, "refresh">;

  constructor(private readonly deps: CompanyResearchDependencies) {
    this.runner = deps.runner ?? new ClaudeAgentRunner();
    this.feedRunner = deps.feedRunner ?? new FeedRunner(deps.client, deps);
  }

  async handle(job: AgentJob): Promise<void> {
    const payload = asRecord(job.payload);
    const context = await this.loadBusinessContext(job.account_id, payload);
    const companyUrl = readString(payload.company_url ?? payload.companyUrl) ?? context.website;
    if (!companyUrl) throw new Error("company_research payload requires company_url or a business context website");

    await this.runResearch(job, {
      context,
      targetName: context.company_name ?? "the company",
      targetUrl: companyUrl,
      competitorId: null,
      runType: "company_research",
      cacheKey: `company_research:${companyUrl}`,
      runInput: { companyUrl, businessContextVersionId: context.id },
      canvasNotes: "Generated by company_research with adversarial verification.",
    });
  }

  async handleCompetitor(job: AgentJob): Promise<void> {
    const payload = asRecord(job.payload);
    const context = await this.loadBusinessContext(job.account_id, payload);
    const competitor = await this.loadCompetitor(job.account_id, payload);
    const competitorUrl = readString(payload.company_url ?? payload.companyUrl ?? payload.competitor_url ?? payload.competitorUrl)
      ?? competitor.website_url;
    if (!competitorUrl) throw new Error("competitor_research requires a competitor with website_url or payload competitor_url");

    await this.runResearch(job, {
      context,
      targetName: competitor.name,
      targetUrl: competitorUrl,
      competitorId: competitor.id,
      runType: "competitor_research",
      cacheKey: `competitor_research:${competitor.id}:${competitorUrl}`,
      runInput: {
        competitor_id: competitor.id,
        competitor_name: competitor.name,
        competitor_url: competitorUrl,
        businessContextVersionId: context.id,
      },
      canvasNotes: `Generated by competitor_research for ${competitor.name} with adversarial verification.`,
    });
  }

  private async runResearch(job: AgentJob, subject: ResearchSubject): Promise<void> {
    await this.markRunRunning(job, subject.runType, subject.runInput);
    const feedResult = await this.feedRunner.refresh({
      accountId: job.account_id,
      feedKey: "firecrawl_scrape",
      cacheKey: subject.cacheKey,
      companyName: subject.targetName,
      companyUrl: subject.targetUrl,
    });
    if (feedResult.health !== "ok") throw new Error(`${subject.runType} crawl failed: ${feedResult.error ?? feedResult.health}`);

    const evidenceIds = await this.writeEvidence(job, feedResult.evidence);
    const routes = await this.loadModelRoutes(job.account_id);
    const extractRoute = requiredRoute(routes, job.account_id, "extract", "extract");
    const escalatedRoute = requiredRoute(routes, job.account_id, "extract_escalated", "extract_escalated");
    assertDifferentRoute(extractRoute, escalatedRoute);
    const verifyRoute = requiredRoute(routes, job.account_id, "research_verify", "research_verify");
    assertVerifierRoute(verifyRoute);

    const extract = await this.extractClaims(extractRoute, subject.context, feedResult.evidence, subject.targetName);
    const escalated = extract.length === 0;
    const claims = escalated
      ? await this.extractClaims(escalatedRoute, subject.context, feedResult.evidence, subject.targetName)
      : extract;
    if (escalated && claims.length === 0) throw new Error("company_research extraction failed validation after escalation");

    await this.writeEscalationMetric(job.account_id, escalated);

    const verified: VerifiedClaim[] = [];
    for (const claim of claims) {
      const evidenceId = evidenceIds[claim.evidenceIndex] ?? evidenceIds[0];
      if (!evidenceId) continue;
      const verdict = await this.verifyClaim(verifyRoute, claim, feedResult.evidence[claim.evidenceIndex] ?? feedResult.evidence[0]);
      verified.push({ ...claim, ...verdict, evidenceId });
    }

    await this.writeVerifiedClaims(job, subject, verified);
    if (subject.runType === "competitor_research" && subject.competitorId) {
      await this.enqueueGapEngine(job, subject.competitorId);
    }
    await this.markRunCompleted(job, {
      run_type: subject.runType,
      company_url: subject.targetUrl,
      competitor_id: subject.competitorId,
      claims: verified.map((claim) => ({
        section_key: claim.sectionKey,
        text: claim.text,
        status: claim.status,
        confidence: earnedConfidence(claim),
      })),
      escalation_rate: escalated ? 1 : 0,
    });
  }

  /**
   * RF-4-1: competitor research chains straight into the gap engine so a single
   * user action ("Research this competitor") yields fresh gaps + Threat Index.
   * Durable like every run: a pending agent_runs row backs the chained job.
   * Failures here must not fail the (already successful) research job.
   */
  private async enqueueGapEngine(job: AgentJob, competitorId: string): Promise<void> {
    try {
      const payload = asRecord(job.payload);
      let agentProfileId = readString(payload.agentProfileId ?? payload.agent_profile_id);
      if (!agentProfileId && job.agent_run_id) {
        const { data: parentRun } = await this.deps.client
          .from("agent_runs")
          .select("agent_profile_id")
          .eq("id", job.agent_run_id)
          .eq("account_id", job.account_id)
          .maybeSingle();
        agentProfileId = parentRun?.agent_profile_id ?? undefined;
      }
      if (!agentProfileId) throw new Error("no agent profile available for chained gap_engine run");
      const nowIso = new Date().toISOString();
      const { data: run, error: runError } = await this.deps.client
        .from("agent_runs")
        .insert({
          account_id: job.account_id,
          agent_profile_id: agentProfileId,
          run_type: "gap_engine",
          trigger_type: "cascade",
          status: "pending",
          input: { competitor_id: competitorId, chained_from_run_id: job.agent_run_id },
          started_at: nowIso,
        })
        .select("id")
        .single();
      if (runError) throw new Error(runError.message);
      const { error: jobError } = await this.deps.client.from("agent_jobs").insert({
        account_id: job.account_id,
        kind: "gap_engine",
        payload: { competitor_id: competitorId, agentProfileId },
        status: "queued",
        agent_run_id: run.id,
        run_after: nowIso,
      });
      if (jobError) throw new Error(jobError.message);
    } catch (error) {
      // Log-and-continue: the research result stands; gap refresh can be re-triggered.
      console.error(`gap_engine chain enqueue failed for competitor ${competitorId}:`, error);
    }
  }

  private async loadBusinessContext(accountId: string, payload: Record<string, unknown>): Promise<BusinessContext> {
    const contextId = readString(payload.business_context_version_id ?? payload.businessContextVersionId);
    let query = this.deps.client
      .from("business_context_versions")
      .select("id, company_name, industry, website")
      .eq("account_id", accountId);
    query = contextId ? query.eq("id", contextId) : query.order("created_at", { ascending: false });
    const { data, error } = await query.limit(1).maybeSingle();
    if (error) throw new Error(`Failed to load business context: ${error.message}`);
    if (!data) throw new Error("company_research requires a business context version");
    return data as BusinessContext;
  }

  private async loadCompetitor(accountId: string, payload: Record<string, unknown>): Promise<CompanyEntity> {
    const competitorId = readString(payload.competitor_id ?? payload.competitorId);
    if (!competitorId) throw new Error("competitor_research payload requires competitor_id");
    const { data, error } = await this.deps.client
      .from("companies")
      .select("id, name, website_url, description, industry, is_competitor")
      .eq("account_id", accountId)
      .eq("id", competitorId)
      .eq("is_competitor", true)
      .limit(1)
      .maybeSingle();
    if (error) throw new Error(`Failed to load competitor: ${error.message}`);
    if (!data) throw new Error("competitor_research requires an account-scoped competitor");
    return data as CompanyEntity;
  }

  private async loadModelRoutes(accountId: string): Promise<ModelRoute[]> {
    const { data, error } = await this.deps.client
      .from("model_routes")
      .select("account_id, route_key, task_class, provider, model_name, params, cost_per_1k_in, cost_per_1k_out")
      .or(`account_id.eq.${accountId},account_id.is.null`)
      .or("task_class.eq.extract,task_class.eq.extract_escalated,task_class.eq.research_verify")
      .order("account_id", { ascending: false, nullsFirst: false });
    if (error) throw new Error(`Failed to load research model routes: ${error.message}`);
    return (data ?? []) as ModelRoute[];
  }

  private async extractClaims(route: ModelRoute, context: BusinessContext, evidence: EvidenceCandidate[], targetName = context.company_name ?? "the company"): Promise<ExtractedClaim[]> {
    const result = await this.runnerForRoute(route).run({
      model: route.model_name,
      modelParams: route.params ?? undefined,
      maxTurns: 12,
      maxBudgetUsd: budgetForRoute(route),
      prompt: `Extract Business Model Canvas claims for ${targetName} from these source excerpts. Return JSON only: {"claims":[{"section_key":"value_propositions","text":"...","confidence":0.7,"evidence_index":0}]}.\n\n${evidencePrompt(evidence)}`,
      systemPrompt: "You extract concise, source-grounded Business Model Canvas claims. Do not invent claims.",
      mcpServers: {},
      allowedTools: [],
    });
    return safeParseClaims(result.resultText);
  }

  private async verifyClaim(route: ModelRoute, claim: ExtractedClaim, evidence: EvidenceCandidate | undefined): Promise<{ status: VerificationStatus; reason: string }> {
    return verifyClaimAgainstExcerpt(this.runnerForRoute(route), route, claim.text, evidence?.excerpt ?? "");
  }

  private runnerForRoute(route: ModelRoute): AgentRunner {
    if (this.deps.runner) return this.deps.runner;
    if (route.provider === "anthropic") return this.runner;
    if (route.provider === "openrouter") {
      return new OpenRouterChatRunner(this.deps.openRouterApiKey, this.deps.fetch);
    }
    throw new Error(`Unsupported model route provider for company_research: ${route.provider}`);
  }

  private async writeEvidence(job: AgentJob, evidence: EvidenceCandidate[]): Promise<string[]> {
    const ids: string[] = [];
    for (const item of evidence) {
      const existingId = await this.findExistingEvidence(job.account_id, item);
      if (existingId) {
        ids.push(existingId);
        continue;
      }
      const { data, error } = await this.deps.client
        .from("evidence_items")
        .insert({
          account_id: job.account_id,
          title: item.title,
          excerpt: item.excerpt ?? null,
          source_url: item.sourceUrl ?? null,
          source_name: item.sourceName ?? null,
          source_type: item.sourceType,
          source_date: item.sourceDate ?? null,
          metadata: item.metadata ?? {},
          created_by_agent_run_id: job.agent_run_id,
        })
        .select("id")
        .single();
      if (error) throw new Error(`Failed to write research evidence: ${error.message}`);
      ids.push(data.id);
    }
    return ids;
  }

  /** RF-3-7: reuse an existing evidence row for the same account/source/excerpt instead of duplicating. */
  private async findExistingEvidence(accountId: string, item: EvidenceCandidate): Promise<string | null> {
    if (!item.sourceUrl || !item.excerpt) return null;
    const { data, error } = await this.deps.client
      .from("evidence_items")
      .select("id")
      .eq("account_id", accountId)
      .eq("source_url", item.sourceUrl)
      .eq("excerpt", item.excerpt)
      .limit(1)
      .maybeSingle();
    if (error) throw new Error(`Failed to check existing evidence: ${error.message}`);
    return data?.id ?? null;
  }

  private async writeVerifiedClaims(job: AgentJob, subject: ResearchSubject, claims: VerifiedClaim[]): Promise<void> {
    const grouped = new Map<SectionKey, VerifiedClaim[]>();
    for (const claim of claims) {
      if (claim.status === "contradicted") {
        await this.writeContradiction(job, subject, claim);
        continue;
      }
      const group = grouped.get(claim.sectionKey) ?? [];
      group.push(claim);
      grouped.set(claim.sectionKey, group);
    }

    for (const [sectionKey, sectionClaims] of grouped) {
      const { error } = await this.deps.client.from("canvas_section_versions").insert({
        account_id: job.account_id,
        business_context_version_id: subject.context.id,
        competitor_id: subject.competitorId,
        section_key: sectionKey,
        section_title: SECTION_LABELS[sectionKey],
        items: sectionClaims.map((claim) => ({
          text: claim.text,
          confidence: earnedConfidence(claim),
          evidence_ids: [claim.evidenceId],
          verification_status: claim.status,
          flags: claim.status === "unsupported" ? ["unsupported"] : [],
        })),
        notes: subject.canvasNotes,
        confidence: average(sectionClaims.map(earnedConfidence)),
        // Enum is (fresh|stale|outdated|unverified) - "fresh" is the verified-good
        // state; verification timing lives in last_verified_at (latent Phase-3 bug:
        // "verified" is not an enum value and failed every live research write).
        freshness_status: "fresh",
        last_verified_at: new Date().toISOString(),
      });
      if (error) throw new Error(`Failed to write researched canvas section: ${error.message}`);
    }
  }

  private async writeContradiction(job: AgentJob, subject: ResearchSubject, claim: VerifiedClaim): Promise<void> {
    const gap = {
      account_id: job.account_id,
      title: `Contradicted ${subject.runType} claim: ${claim.text}`,
      description: claim.reason,
      gap_type: "contradictory",
      severity: "medium",
      affected_sections: [claim.sectionKey],
      evidence_ids: [claim.evidenceId],
      created_by_agent_run_id: job.agent_run_id,
    };
    const { error: gapError } = await this.deps.client.from("gaps").insert(gap);
    if (gapError) throw new Error(`Failed to write contradicted claim gap: ${gapError.message}`);

    const { error: insightError } = await this.deps.client.from("insights").insert({
      account_id: job.account_id,
      severity: "warning",
      title: "Contradicted research claim",
      body: `${claim.text}\n\n${claim.reason}`,
      section_key: claim.sectionKey,
      tags: [subject.runType, "contradicted"],
      evidence_ids: [claim.evidenceId],
      agent_run_id: job.agent_run_id,
    });
    if (insightError) throw new Error(`Failed to write contradicted claim insight: ${insightError.message}`);
  }

  private async writeEscalationMetric(accountId: string, escalated: boolean): Promise<void> {
    const { error } = await this.deps.client.from("metric_snapshots").insert({
      account_id: accountId,
      metric_key: "research.escalation_rate",
      value: escalated ? 1 : 0,
      label: "firecrawl_scrape",
      inputs: { feed_key: "firecrawl_scrape", escalated },
    });
    if (error) throw new Error(`Failed to write escalation metric: ${error.message}`);
  }

  private async markRunRunning(job: AgentJob, runType: ResearchSubject["runType"], input: Record<string, unknown>): Promise<void> {
    if (!job.agent_run_id) return;
    const { error } = await this.deps.client.from("agent_runs").update({
      status: "running",
      run_type: runType,
      input,
      started_at: new Date().toISOString(),
    }).eq("id", job.agent_run_id).eq("account_id", job.account_id);
    if (error) throw new Error(`Failed to mark company research run running: ${error.message}`);
  }

  private async markRunCompleted(job: AgentJob, output: Record<string, unknown>): Promise<void> {
    if (!job.agent_run_id) return;
    const { error } = await this.deps.client.from("agent_runs").update({
      status: "completed",
      output,
      summary: "Research completed with evidence-linked canvas updates.",
      completed_at: new Date().toISOString(),
      error: null,
    }).eq("id", job.agent_run_id).eq("account_id", job.account_id);
    if (error) throw new Error(`Failed to mark company research run completed: ${error.message}`);
  }
}

/**
 * The verification step, exported as a standalone unit so the golden-set test
 * exercises the REAL prompt construction, parsing, and status mapping — not a
 * reimplementation. `route` only needs model_name/params/cost fields here.
 */
export async function verifyClaimAgainstExcerpt(
  runner: AgentRunner,
  route: Pick<ModelRoute, "model_name" | "params" | "cost_per_1k_in" | "cost_per_1k_out">,
  claimText: string,
  excerpt: string,
): Promise<{ status: VerificationStatus; reason: string }> {
  const result = await runner.run({
    model: route.model_name,
    modelParams: route.params ?? undefined,
    maxTurns: 8,
    maxBudgetUsd: budgetForRoute(route),
    prompt: `Classify the claim against the source excerpt as confirmed, unsupported, or contradicted. Return JSON only: {"status":"confirmed","reason":"..."}.\n\nClaim: ${claimText}\n\nSource excerpt:\n${excerpt}`,
    systemPrompt: "You are an adversarial verifier. Never give credit for claims not supported by the excerpt.",
    mcpServers: {},
    allowedTools: [],
  });
  return safeParseVerification(result.resultText);
}

function requiredRoute(routes: ModelRoute[], accountId: string, routeKey: string, taskClass: string): ModelRoute {
  const route = chooseModelRoute(routes.filter((candidate) => candidate.task_class === taskClass), accountId, routeKey, taskClass);
  if (!route) throw new Error(`No model route configured for ${taskClass}/${routeKey}`);
  return route;
}

function safeParseClaims(text: string): ExtractedClaim[] {
  const parsed = parseJsonObject(text);
  if (!parsed) return [];
  if (!Array.isArray(parsed.claims)) return [];
  return parsed.claims.flatMap((claim) => {
    const record = asRecord(claim);
    const sectionKey = record.section_key;
    const claimText = readString(record.text);
    if (!isSectionKey(sectionKey) || !claimText) return [];
    return [{
      sectionKey,
      text: claimText,
      confidence: clampConfidence(record.confidence),
      evidenceIndex: typeof record.evidence_index === "number" ? Math.max(0, Math.floor(record.evidence_index)) : 0,
    }];
  });
}

function safeParseVerification(text: string): { status: VerificationStatus; reason: string } {
  const parsed = parseJsonObject(text);
  if (!parsed) return { status: "unsupported", reason: "verifier output unparseable" };
  const status = parsed.status;
  if (status !== "confirmed" && status !== "unsupported" && status !== "contradicted") {
    return { status: "unsupported", reason: "Verifier returned an invalid status." };
  }
  return { status, reason: readString(parsed.reason) ?? "" };
}

function parseJsonObject(text: string): Record<string, unknown> | null {
  const unfenced = text.replace(/```(?:json)?/gi, "```").replace(/```/g, "").trim();
  const start = unfenced.indexOf("{");
  const end = unfenced.lastIndexOf("}");
  if (start < 0 || end <= start) return null;
  try {
    return asRecord(JSON.parse(unfenced.slice(start, end + 1)));
  } catch {
    return null;
  }
}

function assertDifferentRoute(primary: ModelRoute, escalated: ModelRoute): void {
  if (primary.provider === escalated.provider && primary.model_name === escalated.model_name) {
    throw new Error("extract_escalated route must differ from primary extract route");
  }
}

function assertVerifierRoute(route: ModelRoute): void {
  if (route.task_class !== "research_verify") throw new Error("research_verify route resolved to the wrong task_class");
  if (route.provider !== "anthropic") throw new Error("research_verify route must use a mid-or-better Anthropic model");
  if (!/claude-(haiku|sonnet|opus)/.test(route.model_name)) throw new Error("research_verify route must use a mid-or-better Claude model");
}

function earnedConfidence(claim: VerifiedClaim): number {
  if (claim.status === "unsupported") return Math.min(claim.confidence, 0.5);
  if (claim.status === "contradicted") return 0;
  return claim.confidence;
}

function evidencePrompt(evidence: EvidenceCandidate[]): string {
  return evidence.map((item, index) => `[${index}] ${item.title}\n${item.excerpt ?? ""}`).join("\n\n");
}

function clampConfidence(value: unknown): number {
  return typeof value === "number" && Number.isFinite(value) ? Math.max(0, Math.min(1, value)) : 0.5;
}

function average(values: number[]): number | null {
  if (values.length === 0) return null;
  return Math.round((values.reduce((sum, value) => sum + value, 0) / values.length) * 100) / 100;
}

function budgetForRoute(route: Pick<ModelRoute, "cost_per_1k_in" | "cost_per_1k_out">): number {
  const input = route.cost_per_1k_in ?? 0.002;
  const output = route.cost_per_1k_out ?? 0.01;
  // Floor must cover Claude Agent SDK session overhead, not just the visible
  // prompt: the 2026-07-03 live golden-set run hit error_max_budget_usd at the
  // old $0.056 cap (seeded research_verify costs) before a single verdict.
  return Math.max(0.25, input * 8 + output * 4);
}

function readString(value: unknown): string | undefined {
  return typeof value === "string" && value.length > 0 ? value : undefined;
}
