export const LANDING_AGENT_ACCENTS = {
  Atlas: {
    callsign: "Atlas",
    role: "Chief Strategist",
    section: "The whole canvas",
    line: "Sees the whole board. Sets the agenda.",
    dot: "bg-indigo-500",
    text: "text-indigo-700",
    tint: "bg-indigo-50",
    border: "border-indigo-500",
    initial: "A",
  },
  Compass: {
    callsign: "Compass",
    role: "Market Intelligence",
    section: "Customer Segments",
    line: "Knows your customer better than they do.",
    dot: "bg-teal-500",
    text: "text-teal-700",
    tint: "bg-teal-50",
    initial: "C",
  },
  Forge: {
    callsign: "Forge",
    role: "Product Value",
    section: "Value Propositions",
    line: "Keeps your promise sharp and provable.",
    dot: "bg-orange-500",
    text: "text-orange-700",
    tint: "bg-orange-50",
    initial: "F",
  },
  Relay: {
    callsign: "Relay",
    role: "Distribution",
    section: "Channels",
    line: "Finds the channels you're not using.",
    dot: "bg-sky-500",
    text: "text-sky-700",
    tint: "bg-sky-50",
    initial: "R",
  },
  Anchor: {
    callsign: "Anchor",
    role: "Customer Success",
    section: "Customer Relationships",
    line: "Hears churn coming before it lands.",
    dot: "bg-emerald-500",
    text: "text-emerald-700",
    tint: "bg-emerald-50",
    initial: "A",
  },
  Yield: {
    callsign: "Yield",
    role: "Monetization",
    section: "Revenue Streams",
    line: "Watches every competitor price move.",
    dot: "bg-amber-500",
    text: "text-amber-700",
    tint: "bg-amber-50",
    initial: "Y",
  },
  Vault: {
    callsign: "Vault",
    role: "Assets & Capabilities",
    section: "Key Resources",
    line: "Flags the single points of failure.",
    dot: "bg-slate-500",
    text: "text-slate-700",
    tint: "bg-slate-100",
    initial: "V",
  },
  Tempo: {
    callsign: "Tempo",
    role: "Operations",
    section: "Key Activities",
    line: "Benchmarks how fast you really ship.",
    dot: "bg-violet-500",
    text: "text-violet-700",
    tint: "bg-violet-50",
    initial: "T",
  },
  Envoy: {
    callsign: "Envoy",
    role: "Alliances",
    section: "Key Partners",
    line: "Keeps a live pipeline of partners.",
    dot: "bg-rose-500",
    text: "text-rose-700",
    tint: "bg-rose-50",
    initial: "E",
  },
  Ledger: {
    callsign: "Ledger",
    role: "Cost & Efficiency",
    section: "Cost Structure",
    line: "Drives cost down on a schedule.",
    dot: "bg-zinc-500",
    text: "text-zinc-700",
    tint: "bg-zinc-100",
    initial: "L",
  },
} as const;

export type LandingAgentCallsign = keyof typeof LANDING_AGENT_ACCENTS;
export type LandingAgentAccent = (typeof LANDING_AGENT_ACCENTS)[LandingAgentCallsign];

export const LANDING_CANVAS_AGENT_ORDER: LandingAgentCallsign[] = [
  "Envoy",
  "Tempo",
  "Vault",
  "Forge",
  "Anchor",
  "Relay",
  "Compass",
  "Ledger",
  "Yield",
];
